SELECT CI.FLOW_ID,SFI.COMPOSITE_SCA_ENTITY_ID,CI.COMPOSITE_NAME,SSV.SENSOR_NAME,SSV.STRING_VALUE SENSOR_VALUE,CI.CREATION_DATE,
( CASE WHEN ci.STATE=0 THEN 'STATE_INITIATED'
WHEN ci.STATE=1 THEN 'STATE_OPEN_RUNNING/RECOVERY'
WHEN ci.STATE=2 THEN 'STATE_OPEN_SUSPENDED'
WHEN ci.STATE=3 THEN 'STATE_OPEN_FAULTED'
WHEN ci.STATE=4 THEN 'STATE_CLOSED_PENDING_CANCEL'
WHEN ci.STATE=5 THEN 'STATE_CLOSED_COMPLETED'
WHEN ci.STATE=6 THEN 'STATE_CLOSED_FAULTED'
WHEN ci.STATE=7 THEN 'STATE_CLOSED_CANCELLED'
WHEN ci.STATE=8 THEN 'STATE_CLOSED_ABORTED'
WHEN ci.STATE=9 THEN 'STATE_CLOSED_STALE'
WHEN ci.STATE=10 THEN 'STATE_CLOSED_ROLLED_BACK'
ELSE NULL
END) AS STATE,
SFI.RECOVERABLE_FAULTS
FROM PROD_SOAINFRA.CUBE_INSTANCE CI,
--PROD_SOAINFRA.SCA_ENTITY SE,
PROD_SOAINFRA.SCA_SENSOR_VALUE ssv,
PROD_SOAINFRA.SCA_FLOW_INSTANCE SFI
WHERE 1 = 1
AND ssv.FLOW_ID = CI.FLOW_ID
AND SSV.FLOW_ID = SFi.FLOW_ID
-- para sacar todos los flow-ids
--AND SSV.FLOW_ID = (SELECT MAX(SSV2.FLOW_ID) FROM PROD_SOAINFRA.SCA_SENSOR_VALUE ssv2 where SSV.SENSOR_NAME = SSV2.SENSOR_NAME AND SSV.STRING_VALUE = SSV2.STRING_VALUE)
--AND SFI.COMPOSITE_SCA_ENTITY_ID = SE.ID
AND (SSV.SENSOR_NAME = 'WorkOrder' or SSV.SENSOR_NAME = 'ParentWorkOrder' )
--AND SSV.STRING_VALUE in ('04252431')
and composite_name='INT_082_ELL_WORKORDER_MOD_BAS'
and TO_char(CI.CREATION_DATE, 'YYYY-MM-DD HH24:MI:SS')>'2017-05-31 00:00:00' 
and TO_char(CI.CREATION_DATE, 'YYYY-MM-DD HH24:MI:SS')<'2017-08-01 23:59:59' 
--and SFI.COMPOSITE_SCA_ENTITY_ID in ('300307','300421')
ORDER BY CI.CREATION_DATE;